name: Gavin's Weather App

on:
  pull_request:
    types:
      - opened
      - synchronize
permissions: write-all
jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: AI Code Reviewer
        uses: reviewdog/action-suggester@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tool_name: AI Code Review

      # If you specifically want an OpenAI-based code reviewer, you can use this alternative:
      # - name: AI Code Reviewer
      #   uses: anc95/ChatGPT-CodeReview@main
      #   with:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      #     OPENAI_API_MODEL: "gpt-4" # Optional: defaults to "gpt-4"
      #     exclude: "**/*.json, **/*.md" # Optional: exclude patterns separated by commas