name: Gavin's Weather App

on:
  pull_request:
    types:
      - opened      # Triggers when a PR is opened
      - reopened    # Triggers when a PR is reopened
      - synchronize # Triggers when a commit is pushed to the PR
permissions:
  pull-requests: write
  contents: read    # Add this permission for reading repository contents
jobs:
  setup-openai-review:
    runs-on: ubuntu-latest
    name: Code Review
    steps:
      - name: OpenAI Code Review
        uses: aidar-freeed/ai-codereviewer@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_MODEL: "gpt-4" # You can also use "gpt-3.5-turbo" for a more cost-effective option
          exclude: "**/*.json, **/*.md" # Optional: exclude patterns for files you don't want reviewed